### ISSUE TITLE
Rota para consulta de saldo do usuário

### ISSUE THREAD

**Issue by lvsouza** [lvsouza/lubank-backend#1]
### Introdução

Rota para consulta de saldo da conta do usuário

Rota
`get` - `/api/balance`

**Parâmetros enviados no `header`**

Para esta rota o `authorization` é obrigatório

```YAML
{
    "authorization": "kjhdsfasfajdsgfds"
}
```

**Retorno esperado**
```YAML
{
    "statusCode": 200,
    "data": {
        "balance": "0.00"
    }
}
```

**Retorno em caso de erro**
```YAML
{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "Unauthorized"
}
```
