### ISSUE TITLE
Cadastrar um novo boleto

### ISSUE THREAD

**Issue by lvsouza** [lvsouza/lubank-backend#10]
### Introdução 
Rota que cadastrará um boleto na base de dados. Isso é útil para podermos fazer o pagamento dos boletos posteriormente.

**Rota**
`post` - `/api/billet`

**Parâmetros enviados no `header`**
`authorization` é obrigatório para esta rota
```YAML
{
  "authorization": "..."
}
```

**Retorno esperado se o `authorization` não for enviado**
```YAML
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "\"authorization\" is required",
  "validation": {
    "source": "headers",
    "keys": [
      "authorization"
    ]
  }
}
```

**Retorno esperado se o `authorization` estiver incorreto**
```YAML
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "\"value\" contains a conflict between exclusive peers [password, authorization]",
  "validation": {
    "source": "headers",
    "keys": [
      ""
    ]
  }
}
```

**Parâmetros enviados no `body`**
```YAML
{
    "value": 50.00,
    "code": "12345",
    "favored": "Albertinho"
}
```

**Retorno esperado e caso de sucesso**
```YAML
{
  "statusCode": 201,
  "data": {
    "success": true
  }
}
```

**Retorno esperado se os parâmetros no `body` não forem informados**
```YAML
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "\"value\" is required. \"code\" is required. \"favored\" is required",
  "validation": {
    "source": "body",
    "keys": [
      "value",
      "code",
      "favored"
    ]
  }
}
```

**Retorno esperado se os parâmetros no `body` forem incorretos**
```YAML
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "\"value\" must be larger than or equal to 1. \"code\" is not allowed to be empty. \"favored\" is not allowed to be empty",
  "validation": {
    "source": "body",
    "keys": [
      "value",
      "code",
      "favored"
    ]
  }
}
```
