### ISSUE TITLE
Rota para consultar as informações de boleto

### ISSUE THREAD

**Issue by lvsouza** [lvsouza/lubank-backend#2]
### Introdução
Rota que o consulta as informações de um boleto

**Rota**
`post` - `/api/billet-info`

**Parâmetros enviados no `header`**

`authorization` é obrigatório para esta rota
```YAML
{
    "authorization": "..."
}
```

**Parâmetro enviados no `body`**
```YAML
{
    "code": "000000000"
}
```

**Retorno esperado**
```YAML
{
    "statusCode": 200,
    "data": {
        "code": "00000000001",
        "value": 100,
        "favored": "Juca Pedroso"
    }
}
```

**Retorno esperado caso o boleto não exista**
```YAML
{
    "statusCode": 404,
    "error": "Not Found",
    "message": "Not Found"
}
```

**Retorno esperado caso não esteja logado**
```YAML
{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "Unauthorized"
}
```

**Retorno esperado caso não seja informado o `authorization`**
```YAML
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "\"value\" must contain at least one of [password, authorization]",
    "validation": {
        "source": "headers",
        "keys": [
            ""
        ]
    }
}
```

**Retorno esperado caso não seja informado o `body`**
```YAML
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "\"code\" is required",
    "validation": {
        "source": "body",
        "keys": [
            "code"
        ]
    }
}
```
