### ISSUE TITLE
Rota para realização de resgate

### ISSUE THREAD

**Issue by lvsouza** [lvsouza/lubank-backend#3]
### Introdução
Rota que permitirá que a aplicação faça transferências para outras contas

**Rota**
`post` - `/api/transfer`

**Parâmetros enviados no `header`**

`authorization` é obrigatório para esta rota
```YAML
{
    "authorization": "..."
}
```

**Retorno esperado para token incorreto**
```YAML
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "Unauthorized"
}
```

**Retorno esperado para token não informado**
```YAML
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "\"authorization\" is required",
  "validation": {
    "source": "headers",
    "keys": [
      "authorization"
    ]
  }
}
```

**Parâmetros enviados no `body`**
```YAML
{
    "transferValue": 1.00,
    "accountNumber": "0000000-0",
    "targetCpf": "000.000.000-00"
}
```

**Retorno esperado**
```YAML
{
  "statusCode": 200,
  "data": {
    "success": true
  }
}
```

**Retorno esperado ao não enviar o `body`**
```YAML
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "\"transferValue\" is required. \"accountNumber\" is required. \"targetCpf\" is required",
  "validation": {
    "source": "body",
    "keys": [
      "transferValue",
      "accountNumber",
      "targetCpf"
    ]
  }
}
```

**Retorno esperado ao enviar dados incorretos no `body`**
```YAML
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "\"transferValue\" must be larger than or equal to 1. \"accountNumber\" with value \"000000-0\" fails to match the required pattern: /^\\d{7}\\-\\d{1}$/. \"targetCpf\" with value \"000.00.000-00\" fails to match the required pattern: /^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$/",
  "validation": {
    "source": "body",
    "keys": [
      "transferValue",
      "accountNumber",
      "targetCpf"
    ]
  }
}
```

**Retorno esperado ao tentar fazer uma transferência maior que o saldo em conta**
```YAML
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "Internal Server Error"
}
```
