### ISSUE TITLE
Rota para consulta do extrato da conta do usuário

### ISSUE THREAD

**Issue by lvsouza** [lvsouza/lubank-backend#5]
### Introdução
Rota que retora o extrato de transações feitas pelo usuário

**Rota**
`post` - `/api/transactions`

**Parâmetros enviados no `header`**
`authorization` é obrigatório para esta rota
```JSON
{
    "authorization": "..."
}
```

**Retorno esperado**
```JSON
{
    "statusCode": 200,
    "data": {
        "transactions": [
            {
                "created_at": "2020-08-30 23:01:17",
                "type": 1,
                "value": 50
            },
            {
                "created_at": "2020-08-30 23:17:01",
                "type": 1,
                "value": 50
            },
            {
                "created_at": "2020-08-30 23:17:01",
                "type": 1,
                "value": 50
            }
        ]
    }
}
```

**Retorno esperado se `authorization` estiver invalido**
```YAML
{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "Unauthorized"
}
```

**Retorno esperado se `authorization` não for informado**
```YAML
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "\"value\" must contain at least one of [password, authorization]",
    "validation": {
        "source": "headers",
        "keys": [
            ""
        ]
    }
}
```
