### ISSUE TITLE
Rota que realiza o pagamento de um boleto

### ISSUE THREAD

**Issue by lvsouza** [lvsouza/lubank-backend#6]
### Introdução
Rota para o pagamento de um boleto.
Ao realizar o pagamento de um boleto, o mesmo deve ser apagado dos registros.

**Rota**
`post` - `/api/pay-billet`

**Parâmetros enviados no `header`**
`authorization` é obrigatório para esta rota
```YAML
{
    "authorization": "..."
}
```

**Parâmetro enviado no `body`**
```YAML
{
    "code": "000000000"
}
```

**Retorno esperado**
```YAML
{
    "statusCode": 200,
    "data": {
        "success": true
    }
}
```

**Retorno esperado se: `body` incorreto, saldo insuficiente ou algum erro interno**
```YAML
{
    "statusCode": 406,
    "error": "Not Acceptable",
    "message": "Not Acceptable"
}
```

**Retorno esperado se `authorization` estiver invalido**
```YAML
{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "Unauthorized"
}
```

**Retorno esperado se `authorization` não for informado**
```YAML
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "\"value\" must contain at least one of [password, authorization]",
    "validation": {
        "source": "headers",
        "keys": [
            ""
        ]
    }
}
```

**Retorno esperado se `body` não for informado**
```YAML
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "\"code\" is required",
    "validation": {
        "source": "body",
        "keys": [
            "code"
        ]
    }
}
```
