### ISSUE TITLE
Rota para autenticação

### ISSUE THREAD

**Issue by lvsouza** [lvsouza/lubank-backend#8]
### Introdução
Rota que fará autenticação dos usuários

**Rota**
`get` - `/api/sign`

O `authorization` só será obrigatório se o `email` e a `password` não forem informados.

**headers**
```YAML
{
    "email": "teste@gmail.com",
    "password": "123456",
    "authorization": "dsfasdfasdfasdfasdf"
}
```

**Retorno esperado**
```YAML
{
    "statusCode": 200,
    "data": {
        "user": {
            "email": "rdrogp@gmail.com",
            "name": "Rodrigo da Silva",
            "agency": 1102,
            "account_number": "6448037-8"
        },
        "accessToken": "..."
    }
}
```

**Falha de login**
```YAML
{
    "error": "Bad Request",
    "statusCode": 400,
    "message": "Login failed"
}
```

**Credencias não informadas**
```YAML
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "\"email\" is not allowed to be empty",
    "validation": {
        "source": "headers",
        "keys": [
            "email"
        ]
    }
}
```
