### ISSUE TITLE
Rota para criação de perfil e conta

### ISSUE THREAD

**Issue by lvsouza** [lvsouza/lubank-backend#9]
### Introdução
Rota serve para o cadastro de um novo usuário no lubank

**Rota**
`post` - `/api/signup`

**Parâmetro enviados no header**
```YAML
{
    "password": "123456",
    "email": "teste@gmail.com",
    "name": "Roberto da Silva"
}
```

**Retorno esperado**
```YAML
{
    "statusCode": 201,
    "data": {
        "user": {
            "name": "Rodrigo da Silva",
            "email": "rdrigo@gmail.com",
            "agency": 1102,
            "accountNumber": "6448037-8"
        },
        "accessToken": "..."
    }
}
```

**Parâmetros incorretos**
```YAML
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "\"name\" is not allowed to be empty",
    "validation": {
        "source": "headers",
        "keys": [
            "name"
        ]
    }
}
```

**Erro na criação do usuário**
```YAML
{
    "error": "Bad Request",
    "statusCode": 400,
    "message": "User was not created"
}
```
